export enum Team {
  Blue = "blue",
  Red = "red",
  Spectator = "spectator",
}

export enum DraftAction {
  Ban = "ban",
  Pick = "pick",
}

export enum GameMap {
  AhtenCity = "Ahten City",
  AimisApp = "Ai.Mi's App",
  AtlasLab = "Atlas's Lab",
  ClarionTestChamber = "Clarion Test Chamber",
  DemonDais = "Demon Dais",
  GatesOfObscura = "Gates of Obscura",
  InkysSplashZone = "Inky's Splash Zone",
  NightMarket = "Night Market",
  OniVillage = "Oni Village",
  TaikoTemple = "Taiko Temple",
}

export const ALL_MAPS = [
  {
    name: GameMap.AhtenCity,
    image: "/maps/Ahten_City.png",
    icon: "/maps/Ahten_City_Icon.png",
  },
  {
    name: GameMap.AimisApp,
    image: "/maps/AiMis_App.png",
    icon: "/maps/AiMis_App_Icon.png",
  },
  {
    name: GameMap.AtlasLab,
    image: "/maps/Atlas_Lab.png",
    icon: "/maps/Atlas_Lab_Icon.png",
  },
  {
    name: GameMap.ClarionTestChamber,
    image: "/maps/Clarion_Test_Chamber.png",
    icon: "/maps/Clarion_Test_Chamber_Icon.png",
  },
  {
    name: GameMap.DemonDais,
    image: "/maps/Demon_Dais.png",
    icon: "/maps/Demon_Dais_Icon.png",
  },
  {
    name: GameMap.GatesOfObscura,
    image: "/maps/Gates_of_Obscura.png",
    icon: "/maps/Gates_of_Obscura_Icon.png",
  },
  {
    name: GameMap.InkysSplashZone,
    image: "/maps/Inkys_Splash_Zone.png",
    icon: "/maps/Inkys_Splash_Zone_Icon.png",
  },
  {
    name: GameMap.NightMarket,
    image: "/maps/Night_Market.png",
    icon: "/maps/Night_Market_Icon.png",
  },
  {
    name: GameMap.OniVillage,
    image: "/maps/Oni_Village.png",
    icon: "/maps/Oni_Village_Icon.png",
  },
  {
    name: GameMap.TaikoTemple,
    image: "/maps/Taiko_Temple.png",
    icon: "/maps/Taiko_Temple_Icon.png",
  },
].sort((a, b) => a.name.localeCompare(b.name));

export const CURRENT_MAP_POOL = [
  GameMap.AhtenCity,
  GameMap.AimisApp,
  GameMap.AtlasLab,
  GameMap.ClarionTestChamber,
  GameMap.DemonDais,
  GameMap.GatesOfObscura,
  GameMap.InkysSplashZone,
];

export const TIMER_SECONDS = 30;

export enum Awakening {
  AdrenalineRush = "Adrenaline Rush",
  Aerials = "Aerials",
  AmongTitans = "Among Titans",
  Berserker = "Berserker",
  BigFish = "Big Fish",
  BuiltDifferent = "Built Different",
  BulkUp = "Bulk Up",
  CastToLast = "Cast To Last",
  Catalyst = "Catalyst",
  Chronoboost = "Chronoboost",
  Deadeye = "Deadeye",
  Demolitionist = "Demolitionist",
  Egoist = "Egoist",
  ExplosiveEntrance = "Explosive Entrance",
  ExtraSpecial = "Extra Special",
  FightOrFlight = "Fight or Flight",
  FireUp = "Fire Up!",
  GlassCannon = "Glass Cannon",
  HeavyImpact = "Heavy Impact",
  Hotshot = "Hotshot",
  InnerFocus = "Inner Focus",
  KnifesEdge = "Knife's Edge",
  MightOfTheColossus = "Might of the Colossus",
  MissilePropulsion = "Missile Propulsion",
  Monumentalist = "Monumentalist",
  OmegaInfusedAccelerator = "Omega Infused Accelerator",
  OneTwoPunch = "One-Two Punch",
  OrbDancer = "Orb Dancer",
  OrbPonderer = "Orb Ponderer",
  OrbReplicator = "Orb Replicator",
  PeakPerformance = "Peak Performance",
  PerfectForm = "Perfect Form",
  Primetime = "Primetime",
  PrizeFighter = "Prize Fighter",
  QuickStrike = "Quick Strike",
  Rampage = "Rampage",
  RapidFire = "Rapid Fire",
  RecoveryDrone = "Recovery Drone",
  ReptileRemedy = "Reptile Remedy",
  Reverberation = "Reverberation",
  SiegeMachine = "Siege Machine",
  SparkOfAgility = "Spark of Agility",
  SparkOfFocus = "Spark of Focus",
  SparkOfResilience = "Spark of Resilience",
  SparkOfStrength = "Spark of Strength",
  SparkOfLeadership = "Spark of Leadership",
  SpecializedTraining = "Specialized Training",
  StacksOnStacks = "Stacks On Stacks",
  StaggerSwagger = "Stagger Swagger",
  Stinger = "Stinger",
  SuperSurge = "Super Surge",
  TeamPlayer = "Team Player",
  TempoSwing = "Tempo Swing",
  TimelessCreator = "Timeless Creator",
  TwinDrive = "Twin Drive",
  Unstoppable = "Unstoppable",
}

export const ALL_AWAKENINGS = [
  { name: Awakening.AdrenalineRush, icon: "/awakenings/Adrenaline_Rush.png" },
  { name: Awakening.Aerials, icon: "/awakenings/Aerials.png" },
  { name: Awakening.AmongTitans, icon: "/awakenings/Among_Titans.png" },
  { name: Awakening.Berserker, icon: "/awakenings/Berserker.png" },
  { name: Awakening.BigFish, icon: "/awakenings/Big_Fish.png" },
  { name: Awakening.BuiltDifferent, icon: "/awakenings/Built_Different.png" },
  { name: Awakening.BulkUp, icon: "/awakenings/Bulk_Up.png" },
  { name: Awakening.CastToLast, icon: "/awakenings/Cast_to_Last.png" },
  { name: Awakening.Catalyst, icon: "/awakenings/Catalyst.png" },
  { name: Awakening.Chronoboost, icon: "/awakenings/Chronoboost.png" },
  { name: Awakening.Deadeye, icon: "/awakenings/Deadeye.png" },
  { name: Awakening.Demolitionist, icon: "/awakenings/Demolitionist.png" },
  { name: Awakening.Egoist, icon: "/awakenings/Egoist.png" },
  {
    name: Awakening.ExplosiveEntrance,
    icon: "/awakenings/Explosive_Entrance.png",
  },
  { name: Awakening.ExtraSpecial, icon: "/awakenings/Extra_Special.png" },
  { name: Awakening.FightOrFlight, icon: "/awakenings/Fight_or_Flight.png" },
  { name: Awakening.FireUp, icon: "/awakenings/Fire_Up!.png" },
  { name: Awakening.GlassCannon, icon: "/awakenings/Glass_Cannon.png" },
  { name: Awakening.HeavyImpact, icon: "/awakenings/Heavy_Impact.png" },
  { name: Awakening.Hotshot, icon: "/awakenings/Hotshot.png" },
  { name: Awakening.InnerFocus, icon: "/awakenings/Inner_Focus.png" },
  { name: Awakening.KnifesEdge, icon: "/awakenings/Knife's_Edge.png" },
  {
    name: Awakening.MightOfTheColossus,
    icon: "/awakenings/Might_of_the_Colossus.png",
  },
  {
    name: Awakening.MissilePropulsion,
    icon: "/awakenings/Missile_Propulsion.png",
  },
  { name: Awakening.Monumentalist, icon: "/awakenings/Monumentalist.png" },
  {
    name: Awakening.OmegaInfusedAccelerator,
    icon: "/awakenings/Omega_Infused_Accelerator.png",
  },
  { name: Awakening.OneTwoPunch, icon: "/awakenings/One-Two_Punch.png" },
  { name: Awakening.OrbDancer, icon: "/awakenings/Orb_Dancer.png" },
  { name: Awakening.OrbPonderer, icon: "/awakenings/Orb_Ponderer.png" },
  { name: Awakening.OrbReplicator, icon: "/awakenings/Orb_Replicator.png" },
  { name: Awakening.PeakPerformance, icon: "/awakenings/Peak_Performance.png" },
  { name: Awakening.PerfectForm, icon: "/awakenings/Perfect_Form.png" },
  { name: Awakening.Primetime, icon: "/awakenings/Primetime.png" },
  { name: Awakening.PrizeFighter, icon: "/awakenings/Prize_Fighter.png" },
  { name: Awakening.QuickStrike, icon: "/awakenings/Quick_Strike.png" },
  { name: Awakening.Rampage, icon: "/awakenings/Rampage.png" },
  { name: Awakening.RapidFire, icon: "/awakenings/Rapid_Fire.png" },
  { name: Awakening.RecoveryDrone, icon: "/awakenings/Recovery_Drone.png" },
  { name: Awakening.ReptileRemedy, icon: "/awakenings/Reptile_Remedy.png" },
  { name: Awakening.Reverberation, icon: "/awakenings/Reverberation.png" },
  { name: Awakening.SiegeMachine, icon: "/awakenings/Siege_Machine.png" },
  { name: Awakening.SparkOfAgility, icon: "/awakenings/Spark_of_Agility.png" },
  { name: Awakening.SparkOfFocus, icon: "/awakenings/Spark_of_Focus.png" },
  {
    name: Awakening.SparkOfResilience,
    icon: "/awakenings/Spark_of_Resilience.png",
  },
  {
    name: Awakening.SparkOfStrength,
    icon: "/awakenings/Spark_of_Strength.png",
  },
  {
    name: Awakening.SparkOfLeadership,
    icon: "/awakenings/Spark_of_Leadership.png",
  },
  {
    name: Awakening.SpecializedTraining,
    icon: "/awakenings/Specialized_Training.png",
  },
  { name: Awakening.StacksOnStacks, icon: "/awakenings/Stacks_On_Stacks.png" },
  { name: Awakening.StaggerSwagger, icon: "/awakenings/Stagger_Swagger.png" },
  { name: Awakening.Stinger, icon: "/awakenings/Stinger.png" },
  { name: Awakening.SuperSurge, icon: "/awakenings/Super_Surge.png" },
  { name: Awakening.TeamPlayer, icon: "/awakenings/Team_Player.png" },
  { name: Awakening.TempoSwing, icon: "/awakenings/Tempo_Swing.png" },
  { name: Awakening.TimelessCreator, icon: "/awakenings/Timeless_Creator.png" },
  { name: Awakening.TwinDrive, icon: "/awakenings/Twin_Drive.png" },
  { name: Awakening.Unstoppable, icon: "/awakenings/Unstoppable.png" },
].sort((a, b) => a.name.localeCompare(b.name));

export const CURRENT_AWAKENING_POOL = [
  Awakening.AmongTitans,
  Awakening.Aerials,
  Awakening.Berserker,
  Awakening.BuiltDifferent,
  Awakening.BulkUp,
  Awakening.Deadeye,
  Awakening.Demolitionist,
  Awakening.ExplosiveEntrance,
  Awakening.ExtraSpecial,
  Awakening.GlassCannon,
  Awakening.HeavyImpact,
  Awakening.Hotshot,
  Awakening.MissilePropulsion,
  Awakening.Monumentalist,
  Awakening.OmegaInfusedAccelerator,
  Awakening.OneTwoPunch,
  Awakening.OrbDancer,
  Awakening.PeakPerformance,
  Awakening.ReptileRemedy,
  Awakening.Stinger,
  Awakening.TeamPlayer,
  Awakening.TempoSwing,
  Awakening.TimelessCreator,
  Awakening.SparkOfAgility,
  Awakening.SparkOfFocus,
  Awakening.SparkOfStrength,
  Awakening.AdrenalineRush,
  Awakening.Chronoboost,
  Awakening.RapidFire,
  Awakening.FireUp,
  Awakening.Catalyst,
  Awakening.FightOrFlight,
  Awakening.SiegeMachine,
  Awakening.RecoveryDrone,
].sort((a, b) => a.localeCompare(b));

export const AWAKENING_CONFLICTS: Partial<Record<Awakening, Awakening[]>> = {
  [Awakening.SparkOfResilience]: [
    Awakening.SparkOfStrength,
    Awakening.SparkOfAgility,
    Awakening.SparkOfFocus,
    Awakening.BigFish,
    Awakening.StaggerSwagger,
    Awakening.BulkUp,
    Awakening.PeakPerformance,
    Awakening.TempoSwing,
    Awakening.OrbPonderer,
    Awakening.OrbDancer,
    Awakening.Reverberation,
    Awakening.SparkOfLeadership,
    Awakening.Unstoppable,
    Awakening.RecoveryDrone,
    Awakening.ReptileRemedy,
    Awakening.Catalyst,
  ],
  [Awakening.SparkOfFocus]: [
    Awakening.SparkOfResilience,
    Awakening.SparkOfStrength,
    Awakening.SparkOfAgility,
    Awakening.ExtraSpecial,
    Awakening.RapidFire,
    Awakening.Primetime,
    Awakening.PerfectForm,
    Awakening.TwinDrive,
    Awakening.Hotshot,
    Awakening.AdrenalineRush,
    Awakening.HeavyImpact,
    Awakening.OrbPonderer,
    Awakening.OrbDancer,
    Awakening.Reverberation,
    Awakening.SparkOfLeadership,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.SparkOfStrength]: [
    Awakening.SparkOfFocus,
    Awakening.SparkOfResilience,
    Awakening.SparkOfAgility,
    Awakening.SpecializedTraining,
    Awakening.AdrenalineRush,
    Awakening.PrizeFighter,
    Awakening.HeavyImpact,
    Awakening.BulkUp,
    Awakening.SuperSurge,
    Awakening.GlassCannon,
    Awakening.OrbPonderer,
    Awakening.OrbDancer,
    Awakening.SparkOfLeadership,
    Awakening.OneTwoPunch,
    Awakening.ExplosiveEntrance,
    Awakening.Stinger,
    Awakening.MightOfTheColossus,
    Awakening.Berserker,
  ],
  [Awakening.SparkOfAgility]: [
    Awakening.SparkOfFocus,
    Awakening.SparkOfResilience,
    Awakening.SparkOfStrength,
    Awakening.StacksOnStacks,
    Awakening.Chronoboost,
    Awakening.GlassCannon,
    Awakening.PeakPerformance,
    Awakening.SuperSurge,
    Awakening.Aerials,
    Awakening.FightOrFlight,
    Awakening.OrbDancer,
    Awakening.AmongTitans,
    Awakening.SparkOfLeadership,
    Awakening.OrbPonderer,
    Awakening.ExplosiveEntrance,
    Awakening.Egoist,
    Awakening.KnifesEdge,
    Awakening.OmegaInfusedAccelerator,
  ],
  [Awakening.ExtraSpecial]: [
    Awakening.SpecializedTraining,
    Awakening.TwinDrive,
    Awakening.RapidFire,
    Awakening.SparkOfFocus,
    Awakening.OrbPonderer,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.SpecializedTraining]: [
    Awakening.ExtraSpecial,
    Awakening.SparkOfStrength,
    Awakening.AdrenalineRush,
    Awakening.Stinger,
    Awakening.Deadeye,
    Awakening.BulkUp,
    Awakening.PrizeFighter,
    Awakening.MightOfTheColossus,
  ],
  [Awakening.RapidFire]: [
    Awakening.Primetime,
    Awakening.ExtraSpecial,
    Awakening.TwinDrive,
    Awakening.Hotshot,
    Awakening.SparkOfFocus,
    Awakening.Reverberation,
    Awakening.OrbPonderer,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.Primetime]: [
    Awakening.RapidFire,
    Awakening.SparkOfFocus,
    Awakening.Reverberation,
    Awakening.Stinger,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.Deadeye]: [
    Awakening.MissilePropulsion,
    Awakening.Aerials,
    Awakening.GlassCannon,
    Awakening.SiegeMachine,
    Awakening.Stinger,
    Awakening.SpecializedTraining,
  ],
  [Awakening.MissilePropulsion]: [
    Awakening.Deadeye,
    Awakening.Aerials,
    Awakening.GlassCannon,
    Awakening.SiegeMachine,
    Awakening.Stinger,
  ],
  [Awakening.PerfectForm]: [
    Awakening.HeavyImpact,
    Awakening.TempoSwing,
    Awakening.SparkOfFocus,
    Awakening.OneTwoPunch,
    Awakening.OrbPonderer,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.TwinDrive]: [
    Awakening.SuperSurge,
    Awakening.Chronoboost,
    Awakening.Aerials,
    Awakening.RapidFire,
    Awakening.ExtraSpecial,
    Awakening.SparkOfFocus,
    Awakening.FightOrFlight,
    Awakening.OrbPonderer,
    Awakening.ExplosiveEntrance,
    Awakening.InnerFocus,
  ],
  [Awakening.SuperSurge]: [
    Awakening.TwinDrive,
    Awakening.Chronoboost,
    Awakening.Aerials,
    Awakening.SparkOfStrength,
    Awakening.SparkOfAgility,
    Awakening.ExplosiveEntrance,
    Awakening.Stinger,
    Awakening.MightOfTheColossus,
  ],
  [Awakening.CastToLast]: [
    Awakening.Chronoboost,
    Awakening.TimelessCreator,
    Awakening.Monumentalist,
    Awakening.SiegeMachine,
  ],
  [Awakening.Monumentalist]: [
    Awakening.TimelessCreator,
    Awakening.CastToLast,
    Awakening.SiegeMachine,
  ],
  [Awakening.TimelessCreator]: [
    Awakening.Monumentalist,
    Awakening.CastToLast,
    Awakening.SiegeMachine,
  ],
  [Awakening.Hotshot]: [
    Awakening.RapidFire,
    Awakening.SparkOfFocus,
    Awakening.TeamPlayer,
    Awakening.Reverberation,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.AdrenalineRush]: [
    Awakening.PrizeFighter,
    Awakening.SpecializedTraining,
    Awakening.OneTwoPunch,
    Awakening.SparkOfFocus,
    Awakening.Reverberation,
    Awakening.Demolitionist,
    Awakening.Stinger,
    Awakening.MightOfTheColossus,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.PrizeFighter]: [
    Awakening.AdrenalineRush,
    Awakening.SparkOfStrength,
    Awakening.RecoveryDrone,
    Awakening.Stinger,
    Awakening.SpecializedTraining,
    Awakening.MightOfTheColossus,
    Awakening.Berserker,
  ],
  [Awakening.Stinger]: [
    Awakening.RapidFire,
    Awakening.MissilePropulsion,
    Awakening.AdrenalineRush,
    Awakening.SparkOfStrength,
    Awakening.HeavyImpact,
    Awakening.OneTwoPunch,
    Awakening.BulkUp,
    Awakening.SuperSurge,
    Awakening.ExplosiveEntrance,
    Awakening.SpecializedTraining,
    Awakening.Deadeye,
    Awakening.Primetime,
    Awakening.PrizeFighter,
    Awakening.MightOfTheColossus,
    Awakening.Berserker,
  ],
  [Awakening.BuiltDifferent]: [
    Awakening.BigFish,
    Awakening.HeavyImpact,
    Awakening.SparkOfStrength,
    Awakening.Demolitionist,
    Awakening.RecoveryDrone,
    Awakening.ExplosiveEntrance,
    Awakening.Rampage,
    Awakening.MightOfTheColossus,
  ],
  [Awakening.BigFish]: [
    Awakening.BuiltDifferent,
    Awakening.SparkOfResilience,
    Awakening.PeakPerformance,
    Awakening.BulkUp,
    Awakening.StaggerSwagger,
    Awakening.TempoSwing,
    Awakening.Reverberation,
    Awakening.Demolitionist,
    Awakening.Unstoppable,
    Awakening.RecoveryDrone,
    Awakening.ReptileRemedy,
    Awakening.Rampage,
    Awakening.MightOfTheColossus,
    Awakening.Catalyst,
  ],
  [Awakening.StaggerSwagger]: [
    Awakening.BigFish,
    Awakening.BulkUp,
    Awakening.PeakPerformance,
    Awakening.SparkOfResilience,
    Awakening.TempoSwing,
    Awakening.Stinger,
    Awakening.Reverberation,
    Awakening.AmongTitans,
    Awakening.FightOrFlight,
    Awakening.Unstoppable,
    Awakening.ReptileRemedy,
    Awakening.Rampage,
    Awakening.Catalyst,
    Awakening.Egoist,
    Awakening.KnifesEdge,
    Awakening.OmegaInfusedAccelerator,
    Awakening.Berserker,
  ],
  [Awakening.OneTwoPunch]: [
    Awakening.PerfectForm,
    Awakening.HeavyImpact,
    Awakening.SparkOfStrength,
    Awakening.AdrenalineRush,
    Awakening.ExplosiveEntrance,
    Awakening.Stinger,
    Awakening.MightOfTheColossus,
  ],
  [Awakening.StacksOnStacks]: [
    Awakening.StaggerSwagger,
    Awakening.GlassCannon,
    Awakening.SparkOfAgility,
    Awakening.Rampage,
    Awakening.AmongTitans,
    Awakening.FightOrFlight,
    Awakening.OrbDancer,
    Awakening.Unstoppable,
    Awakening.RecoveryDrone,
    Awakening.ReptileRemedy,
    Awakening.Egoist,
    Awakening.KnifesEdge,
    Awakening.OmegaInfusedAccelerator,
  ],
  [Awakening.Chronoboost]: [
    Awakening.SuperSurge,
    Awakening.CastToLast,
    Awakening.Aerials,
    Awakening.TwinDrive,
    Awakening.SparkOfAgility,
    Awakening.ExplosiveEntrance,
  ],
  [Awakening.GlassCannon]: [
    Awakening.StacksOnStacks,
    Awakening.Deadeye,
    Awakening.MissilePropulsion,
    Awakening.SparkOfAgility,
    Awakening.SparkOfStrength,
    Awakening.AmongTitans,
    Awakening.KnifesEdge,
    Awakening.OrbDancer,
    Awakening.Unstoppable,
    Awakening.MightOfTheColossus,
    Awakening.Egoist,
    Awakening.FightOrFlight,
    Awakening.OmegaInfusedAccelerator,
    Awakening.Berserker,
  ],
  [Awakening.HeavyImpact]: [
    Awakening.BuiltDifferent,
    Awakening.PerfectForm,
    Awakening.OneTwoPunch,
    Awakening.SparkOfStrength,
    Awakening.SparkOfFocus,
    Awakening.Reverberation,
    Awakening.OrbPonderer,
    Awakening.ExplosiveEntrance,
    Awakening.Stinger,
    Awakening.MightOfTheColossus,
  ],
  [Awakening.PeakPerformance]: [
    Awakening.StaggerSwagger,
    Awakening.BigFish,
    Awakening.BulkUp,
    Awakening.SparkOfResilience,
    Awakening.SparkOfAgility,
    Awakening.TempoSwing,
    Awakening.ReptileRemedy,
    Awakening.AmongTitans,
    Awakening.Reverberation,
    Awakening.OrbDancer,
    Awakening.Unstoppable,
    Awakening.Catalyst,
    Awakening.Egoist,
    Awakening.FightOrFlight,
    Awakening.KnifesEdge,
    Awakening.OmegaInfusedAccelerator,
  ],
  [Awakening.BulkUp]: [
    Awakening.StaggerSwagger,
    Awakening.BigFish,
    Awakening.PeakPerformance,
    Awakening.SparkOfResilience,
    Awakening.SparkOfStrength,
    Awakening.TempoSwing,
    Awakening.Stinger,
    Awakening.Reverberation,
    Awakening.Unstoppable,
    Awakening.SpecializedTraining,
    Awakening.ReptileRemedy,
    Awakening.MightOfTheColossus,
    Awakening.Catalyst,
    Awakening.Berserker,
  ],
  [Awakening.Aerials]: [
    Awakening.Deadeye,
    Awakening.MissilePropulsion,
    Awakening.SuperSurge,
    Awakening.Chronoboost,
    Awakening.SparkOfAgility,
    Awakening.ExplosiveEntrance,
    Awakening.SiegeMachine,
  ],
  [Awakening.QuickStrike]: [
    Awakening.Hotshot,
    Awakening.BuiltDifferent,
    Awakening.BigFish,
    Awakening.Demolitionist,
    Awakening.TeamPlayer,
    Awakening.Catalyst,
    Awakening.Egoist,
    Awakening.FireUp,
    Awakening.FightOrFlight,
    Awakening.RecoveryDrone,
    Awakening.Rampage,
    Awakening.MightOfTheColossus,
    Awakening.OmegaInfusedAccelerator,
  ],
  [Awakening.TempoSwing]: [
    Awakening.PerfectForm,
    Awakening.BigFish,
    Awakening.BulkUp,
    Awakening.PeakPerformance,
    Awakening.SparkOfResilience,
    Awakening.StaggerSwagger,
    Awakening.Reverberation,
    Awakening.Unstoppable,
    Awakening.Stinger,
    Awakening.Rampage,
    Awakening.ReptileRemedy,
  ],
  [Awakening.OrbDancer]: [
    Awakening.OrbPonderer,
    Awakening.StacksOnStacks,
    Awakening.StaggerSwagger,
    Awakening.SparkOfAgility,
    Awakening.SparkOfFocus,
    Awakening.SparkOfResilience,
    Awakening.SparkOfStrength,
    Awakening.GlassCannon,
    Awakening.PeakPerformance,
    Awakening.AmongTitans,
    Awakening.OrbReplicator,
    Awakening.SparkOfLeadership,
    Awakening.Unstoppable,
    Awakening.RecoveryDrone,
    Awakening.ReptileRemedy,
    Awakening.Egoist,
    Awakening.FightOrFlight,
    Awakening.KnifesEdge,
  ],
  [Awakening.OrbPonderer]: [
    Awakening.OrbDancer,
    Awakening.SparkOfFocus,
    Awakening.SparkOfResilience,
    Awakening.SparkOfStrength,
    Awakening.SparkOfAgility,
    Awakening.RapidFire,
    Awakening.TwinDrive,
    Awakening.PerfectForm,
    Awakening.HeavyImpact,
    Awakening.ExtraSpecial,
    Awakening.Reverberation,
    Awakening.OrbReplicator,
    Awakening.SparkOfLeadership,
    Awakening.Unstoppable,
    Awakening.RecoveryDrone,
    Awakening.ReptileRemedy,
    Awakening.Egoist,
    Awakening.FightOrFlight,
    Awakening.KnifesEdge,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.OrbReplicator]: [
    Awakening.OrbPonderer,
    Awakening.OrbDancer,
    Awakening.SparkOfLeadership,
    Awakening.FireUp,
    Awakening.TeamPlayer,
    Awakening.AmongTitans,
  ],
  [Awakening.Reverberation]: [
    Awakening.BigFish,
    Awakening.BulkUp,
    Awakening.PeakPerformance,
    Awakening.SparkOfResilience,
    Awakening.TempoSwing,
    Awakening.SparkOfFocus,
    Awakening.RapidFire,
    Awakening.OrbPonderer,
    Awakening.HeavyImpact,
    Awakening.AdrenalineRush,
    Awakening.Hotshot,
    Awakening.Unstoppable,
    Awakening.ReptileRemedy,
    Awakening.Catalyst,
    Awakening.Berserker,
    Awakening.InnerFocus,
  ],
  [Awakening.Catalyst]: [
    Awakening.Egoist,
    Awakening.FireUp,
    Awakening.QuickStrike,
    Awakening.BulkUp,
    Awakening.Reverberation,
    Awakening.PeakPerformance,
    Awakening.ReptileRemedy,
    Awakening.Unstoppable,
    Awakening.BigFish,
    Awakening.RecoveryDrone,
    Awakening.StaggerSwagger,
    Awakening.SparkOfResilience,
  ],
  [Awakening.Egoist]: [
    Awakening.FireUp,
    Awakening.Catalyst,
    Awakening.QuickStrike,
    Awakening.StaggerSwagger,
    Awakening.PeakPerformance,
    Awakening.AmongTitans,
    Awakening.SparkOfAgility,
    Awakening.KnifesEdge,
    Awakening.OrbDancer,
    Awakening.OrbPonderer,
    Awakening.StacksOnStacks,
    Awakening.GlassCannon,
    Awakening.FightOrFlight,
    Awakening.OmegaInfusedAccelerator,
  ],
  [Awakening.FireUp]: [
    Awakening.Catalyst,
    Awakening.Egoist,
    Awakening.AmongTitans,
    Awakening.OrbReplicator,
    Awakening.TeamPlayer,
    Awakening.SparkOfLeadership,
    Awakening.QuickStrike,
  ],
  [Awakening.AmongTitans]: [
    Awakening.SparkOfAgility,
    Awakening.FireUp,
    Awakening.OrbReplicator,
    Awakening.OrbDancer,
    Awakening.StacksOnStacks,
    Awakening.StaggerSwagger,
    Awakening.PeakPerformance,
    Awakening.GlassCannon,
    Awakening.FightOrFlight,
    Awakening.TeamPlayer,
    Awakening.SparkOfLeadership,
    Awakening.MightOfTheColossus,
    Awakening.Egoist,
    Awakening.KnifesEdge,
    Awakening.OmegaInfusedAccelerator,
  ],
  [Awakening.Demolitionist]: [
    Awakening.BuiltDifferent,
    Awakening.BigFish,
    Awakening.AdrenalineRush,
    Awakening.QuickStrike,
    Awakening.RecoveryDrone,
    Awakening.Rampage,
    Awakening.MightOfTheColossus,
  ],
  [Awakening.FightOrFlight]: [
    Awakening.TwinDrive,
    Awakening.StaggerSwagger,
    Awakening.AmongTitans,
    Awakening.StacksOnStacks,
    Awakening.KnifesEdge,
    Awakening.QuickStrike,
    Awakening.Rampage,
    Awakening.SparkOfAgility,
    Awakening.PeakPerformance,
    Awakening.GlassCannon,
    Awakening.OrbDancer,
    Awakening.OrbPonderer,
    Awakening.Egoist,
    Awakening.OmegaInfusedAccelerator,
  ],
  [Awakening.KnifesEdge]: [
    Awakening.FightOrFlight,
    Awakening.GlassCannon,
    Awakening.Unstoppable,
    Awakening.RecoveryDrone,
    Awakening.PeakPerformance,
    Awakening.StacksOnStacks,
    Awakening.StaggerSwagger,
    Awakening.AmongTitans,
    Awakening.Egoist,
    Awakening.SparkOfAgility,
    Awakening.OrbDancer,
    Awakening.OrbPonderer,
    Awakening.OmegaInfusedAccelerator,
    Awakening.Berserker,
  ],
  [Awakening.TeamPlayer]: [
    Awakening.FireUp,
    Awakening.OrbReplicator,
    Awakening.QuickStrike,
    Awakening.AmongTitans,
    Awakening.Hotshot,
    Awakening.SparkOfLeadership,
  ],
  [Awakening.SparkOfLeadership]: [
    Awakening.SparkOfStrength,
    Awakening.SparkOfFocus,
    Awakening.SparkOfResilience,
    Awakening.SparkOfAgility,
    Awakening.OrbReplicator,
    Awakening.OrbPonderer,
    Awakening.OrbDancer,
    Awakening.TeamPlayer,
    Awakening.FireUp,
    Awakening.AmongTitans,
  ],
  [Awakening.Unstoppable]: [
    Awakening.BigFish,
    Awakening.StaggerSwagger,
    Awakening.StacksOnStacks,
    Awakening.PeakPerformance,
    Awakening.BulkUp,
    Awakening.Reverberation,
    Awakening.TempoSwing,
    Awakening.OrbDancer,
    Awakening.OrbPonderer,
    Awakening.GlassCannon,
    Awakening.SparkOfResilience,
    Awakening.RecoveryDrone,
    Awakening.KnifesEdge,
    Awakening.ReptileRemedy,
    Awakening.Rampage,
    Awakening.Catalyst,
  ],
  [Awakening.RecoveryDrone]: [
    Awakening.BuiltDifferent,
    Awakening.BigFish,
    Awakening.Demolitionist,
    Awakening.Unstoppable,
    Awakening.StacksOnStacks,
    Awakening.KnifesEdge,
    Awakening.OrbDancer,
    Awakening.OrbPonderer,
    Awakening.PrizeFighter,
    Awakening.SparkOfResilience,
    Awakening.QuickStrike,
    Awakening.ReptileRemedy,
    Awakening.Rampage,
    Awakening.MightOfTheColossus,
    Awakening.StaggerSwagger,
    Awakening.Catalyst,
  ],
  [Awakening.ExplosiveEntrance]: [
    Awakening.BuiltDifferent,
    Awakening.HeavyImpact,
    Awakening.SuperSurge,
    Awakening.Aerials,
    Awakening.Chronoboost,
    Awakening.OneTwoPunch,
    Awakening.SparkOfStrength,
    Awakening.SparkOfAgility,
    Awakening.TwinDrive,
    Awakening.Stinger,
    Awakening.MightOfTheColossus,
  ],
  [Awakening.SiegeMachine]: [
    Awakening.Aerials,
    Awakening.MissilePropulsion,
    Awakening.Monumentalist,
    Awakening.TimelessCreator,
    Awakening.CastToLast,
    Awakening.Deadeye,
  ],
  [Awakening.ReptileRemedy]: [
    Awakening.BigFish,
    Awakening.BulkUp,
    Awakening.Reverberation,
    Awakening.PeakPerformance,
    Awakening.SparkOfResilience,
    Awakening.TempoSwing,
    Awakening.Unstoppable,
    Awakening.StaggerSwagger,
    Awakening.RecoveryDrone,
    Awakening.Rampage,
    Awakening.StacksOnStacks,
    Awakening.OrbPonderer,
    Awakening.OrbDancer,
    Awakening.Catalyst,
  ],
  [Awakening.Rampage]: [
    Awakening.BigFish,
    Awakening.BuiltDifferent,
    Awakening.RecoveryDrone,
    Awakening.Demolitionist,
    Awakening.QuickStrike,
    Awakening.FightOrFlight,
    Awakening.Unstoppable,
    Awakening.StacksOnStacks,
    Awakening.StaggerSwagger,
    Awakening.ReptileRemedy,
  ],
  [Awakening.MightOfTheColossus]: [
    Awakening.SpecializedTraining,
    Awakening.PrizeFighter,
    Awakening.AdrenalineRush,
    Awakening.OneTwoPunch,
    Awakening.HeavyImpact,
    Awakening.BulkUp,
    Awakening.SuperSurge,
    Awakening.GlassCannon,
    Awakening.ExplosiveEntrance,
    Awakening.Stinger,
    Awakening.SparkOfStrength,
    Awakening.BigFish,
    Awakening.BuiltDifferent,
    Awakening.RecoveryDrone,
    Awakening.Demolitionist,
    Awakening.AmongTitans,
    Awakening.QuickStrike,
    Awakening.TempoSwing,
    Awakening.Berserker,
  ],
  [Awakening.OmegaInfusedAccelerator]: [
    Awakening.AmongTitans,
    Awakening.GlassCannon,
    Awakening.PeakPerformance,
    Awakening.StacksOnStacks,
    Awakening.QuickStrike,
    Awakening.Egoist,
    Awakening.FightOrFlight,
    Awakening.KnifesEdge,
    Awakening.SparkOfAgility,
    Awakening.StaggerSwagger,
  ],
  [Awakening.Berserker]: [
    Awakening.AdrenalineRush,
    Awakening.BulkUp,
    Awakening.ExtraSpecial,
    Awakening.GlassCannon,
    Awakening.Hotshot,
    Awakening.InnerFocus,
    Awakening.KnifesEdge,
    Awakening.MightOfTheColossus,
    Awakening.OrbPonderer,
    Awakening.PerfectForm,
    Awakening.Primetime,
    Awakening.PrizeFighter,
    Awakening.Stinger,
    Awakening.RapidFire,
    Awakening.Reverberation,
    Awakening.SparkOfFocus,
    Awakening.SparkOfStrength,
    Awakening.StaggerSwagger,
  ],
  [Awakening.InnerFocus]: [
    Awakening.AdrenalineRush,
    Awakening.Berserker,
    Awakening.ExtraSpecial,
    Awakening.Hotshot,
    Awakening.OrbPonderer,
    Awakening.PerfectForm,
    Awakening.Primetime,
    Awakening.RapidFire,
    Awakening.Reverberation,
    Awakening.SparkOfFocus,
    Awakening.TwinDrive,
  ],
};

export const DEFAULT_BANNED_AWAKENINGS = [
  Awakening.SparkOfLeadership,
  Awakening.TeamPlayer,
  Awakening.FireUp,
];

export enum StrikerDirection {
  Left = "left",
  Right = "right",
}

export enum Striker {
  AiMi = "Ai.Mi",
  Asher = "Asher",
  Atlas = "Atlas",
  Drekar = "Drek'ar",
  Dubu = "Dubu",
  Era = "Era",
  Estelle = "Estelle",
  Finii = "Finii",
  Juliette = "Juliette",
  Juno = "Juno",
  Kai = "Kai",
  Kazan = "Kazan",
  Luna = "Luna",
  Mako = "Mako",
  Nao = "Nao",
  Octavia = "Octavia",
  Rasmus = "Rasmus",
  Rune = "Rune",
  Vyce = "Vyce",
  X = "X",
  Zentaro = "Zentaro",
}

export const ALL_STRIKERS = [
  {
    name: Striker.AiMi,
    splash: "/strikers/Ai.Mi_splash.png",
    icon: "/strikers/Ai.Mi_icon.png",
    facing: StrikerDirection.Right,
  },
  {
    name: Striker.Asher,
    splash: "/strikers/Asher_splash.png",
    icon: "/strikers/Asher_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Atlas,
    splash: "/strikers/Atlas_splash.png",
    icon: "/strikers/Atlas_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Drekar,
    splash: "/strikers/Drek'ar_splash.png",
    icon: "/strikers/Drek'ar_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Dubu,
    splash: "/strikers/Dubu_splash.png",
    icon: "/strikers/Dubu_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Era,
    splash: "/strikers/Era_splash.png",
    icon: "/strikers/Era_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Estelle,
    splash: "/strikers/Estelle_splash.png",
    icon: "/strikers/Estelle_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Finii,
    splash: "/strikers/Finii_splash.png",
    icon: "/strikers/Finii_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Juliette,
    splash: "/strikers/Juliette_splash.png",
    icon: "/strikers/Juliette_icon.png",
    facing: StrikerDirection.Right,
  },
  {
    name: Striker.Juno,
    splash: "/strikers/Juno_splash.png",
    icon: "/strikers/Juno_icon.png",
    facing: StrikerDirection.Right,
  },
  {
    name: Striker.Kai,
    splash: "/strikers/Kai_splash.png",
    icon: "/strikers/Kai_icon.png",
    facing: StrikerDirection.Right,
  },
  {
    name: Striker.Kazan,
    splash: "/strikers/Kazan_splash.png",
    icon: "/strikers/Kazan_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Luna,
    splash: "/strikers/Luna_splash.png",
    icon: "/strikers/Luna_icon.png",
    facing: StrikerDirection.Right,
  },
  {
    name: Striker.Mako,
    splash: "/strikers/Mako_splash.png",
    icon: "/strikers/Mako_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Nao,
    splash: "/strikers/Nao_Splash.png",
    icon: "/strikers/Nao_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Octavia,
    splash: "/strikers/Octavia_splash.png",
    icon: "/strikers/Octavia_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Rasmus,
    splash: "/strikers/Rasmus_splash.png",
    icon: "/strikers/Rasmus_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Rune,
    splash: "/strikers/Rune_splash.png",
    icon: "/strikers/Rune_icon.png",
    facing: StrikerDirection.Right,
  },
  {
    name: Striker.Vyce,
    splash: "/strikers/Vyce_splash.png",
    icon: "/strikers/Vyce_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.X,
    splash: "/strikers/X_splash.png",
    icon: "/strikers/X_icon.png",
    facing: StrikerDirection.Left,
  },
  {
    name: Striker.Zentaro,
    splash: "/strikers/Zentaro_splash.png",
    icon: "/strikers/Zentaro_icon.png",
    facing: StrikerDirection.Left,
  },
].sort((a, b) => a.name.localeCompare(b.name));
