export enum Team {
  Blue = "blue",
  Red = "red",
  Spectator = "spectator",
}

export enum DraftAction {
  Ban = "ban",
  Pick = "pick",
}

export enum GameMap {
  AhtenCity = "Ahten City",
  AimisApp = "Aimi's App",
  AtlasLab = "Atlas's Lab",
  ClarionTestChamber = "Clarion Test Chamber",
  DemonDais = "Demon Dais",
  GatesOfObscura = "Gates of Obscura",
  InkysSplashZone = "Inky's Splash Zone",
  NightMarket = "Night Market",
  OniVillage = "Oni Village",
  TaikoTemple = "Taiko Temple",
}

export const ALL_MAPS = [
  {
    name: GameMap.AhtenCity,
    image: "/maps/Ahten_City.png",
    icon: "/maps/Ahten_City_Icon.png",
  },
  {
    name: GameMap.AimisApp,
    image: "/maps/AiMis_App.png",
    icon: "/maps/AiMis_App_Icon.png",
  },
  {
    name: GameMap.AtlasLab,
    image: "/maps/Atlas_Lab.png",
    icon: "/maps/Atlas_Lab_Icon.png",
  },
  {
    name: GameMap.ClarionTestChamber,
    image: "/maps/Clarion_Test_Chamber.png",
    icon: "/maps/Clarion_Test_Chamber_Icon.png",
  },
  {
    name: GameMap.DemonDais,
    image: "/maps/Demon_Dais.png",
    icon: "/maps/Demon_Dais_Icon.png",
  },
  {
    name: GameMap.GatesOfObscura,
    image: "/maps/Gates_of_Obscura.png",
    icon: "/maps/Gates_of_Obscura_Icon.png",
  },
  {
    name: GameMap.InkysSplashZone,
    image: "/maps/Inkys_Splash_Zone.png",
    icon: "/maps/Inkys_Splash_Zone_Icon.png",
  },
  {
    name: GameMap.NightMarket,
    image: "/maps/Night_Market.png",
    icon: "/maps/Night_Market_Icon.png",
  },
  {
    name: GameMap.OniVillage,
    image: "/maps/Oni_Village.png",
    icon: "/maps/Oni_Village_Icon.png",
  },
  {
    name: GameMap.TaikoTemple,
    image: "/maps/Taiko_Temple.png",
    icon: "/maps/Taiko_Temple_Icon.png",
  },
];

export const CURRENT_MAP_POOL = [
  GameMap.AhtenCity,
  GameMap.AimisApp,
  GameMap.AtlasLab,
  GameMap.ClarionTestChamber,
  GameMap.DemonDais,
  GameMap.GatesOfObscura,
  GameMap.InkysSplashZone,
];

export const TIMER_SECONDS = 30;

export enum Awakening {
  AdrenalineRush = "Adrenaline Rush",
  Aerials = "Aerials",
  AmongTitans = "Among Titans",
  Berserker = "Berserker",
  BigFish = "Big Fish",
  BuiltDifferent = "Built Different",
  BulkUp = "Bulk Up",
  CastToLast = "Cast To Last",
  Catalyst = "Catalyst",
  Chronoboost = "Chronoboost",
  Deadeye = "Deadeye",
  Demolitionist = "Demolitionist",
  Egoist = "Egoist",
  ExplosiveEntrance = "Explosive Entrance",
  ExtraSpecial = "Extra Special",
  FightOrFlight = "Fight or Flight",
  FireUp = "Fire Up!",
  GlassCannon = "Glass Cannon",
  HeavyImpact = "Heavy Impact",
  Hotshot = "Hotshot",
  InnerFocus = "Inner Focus",
  KnifesEdge = "Knife's Edge",
  MightOfTheColossus = "Might of the Colossus",
  MissilePropulsion = "Missile Propulsion",
  Monumentalist = "Monumentalist",
  OmegaInfusedAccelerator = "Omega Infused Accelerator",
  OneTwoPunch = "One-Two Punch",
  OrbDancer = "Orb Dancer",
  OrbPonderer = "Orb Ponderer",
  OrbReplicator = "Orb Replicator",
  PeakPerformance = "Peak Performance",
  PerfectForm = "Perfect Form",
  Primetime = "Primetime",
  PrizeFighter = "Prize Fighter",
  QuickStrike = "Quick Strike",
  Rampage = "Rampage",
  RapidFire = "Rapid Fire",
  RecoveryDrone = "Recovery Drone",
  ReptileRemedy = "Reptile Remedy",
  Reverberation = "Reverberation",
  SiegeMachine = "Siege Machine",
  SparkOfAgility = "Spark of Agility",
  SparkOfFocus = "Spark of Focus",
  SparkOfResilience = "Spark of Resilience",
  SparkOfStrength = "Spark of Strength",
  SpecializedTraining = "Specialized Training",
  StacksOnStacks = "Stacks On Stacks",
  StaggerSwagger = "Stagger Swagger",
  Stinger = "Stinger",
  SuperSurge = "Super Surge",
  TeamPlayer = "Team Player",
  TempoSwing = "Tempo Swing",
  TimelessCreator = "Timeless Creator",
  TwinDrive = "Twin Drive",
  Unstoppable = "Unstoppable",
}

export const ALL_AWAKENINGS = [
  { name: Awakening.AdrenalineRush, icon: "/awakenings/Adrenaline_Rush.png" },
  { name: Awakening.Aerials, icon: "/awakenings/Aerials.png" },
  { name: Awakening.AmongTitans, icon: "/awakenings/Among_Titans.png" },
  { name: Awakening.Berserker, icon: "/awakenings/Berserker.png" },
  { name: Awakening.BigFish, icon: "/awakenings/Big_Fish.png" },
  { name: Awakening.BuiltDifferent, icon: "/awakenings/Built_Different.png" },
  { name: Awakening.BulkUp, icon: "/awakenings/Bulk_Up.png" },
  { name: Awakening.CastToLast, icon: "/awakenings/Cast_To_Last.png" },
  { name: Awakening.Catalyst, icon: "/awakenings/Catalyst.png" },
  { name: Awakening.Chronoboost, icon: "/awakenings/Chronoboost.png" },
  { name: Awakening.Deadeye, icon: "/awakenings/Deadeye.png" },
  { name: Awakening.Demolitionist, icon: "/awakenings/Demolitionist.png" },
  { name: Awakening.Egoist, icon: "/awakenings/Egoist.png" },
  { name: Awakening.ExplosiveEntrance, icon: "/awakenings/Explosive_Entrance.png" },
  { name: Awakening.ExtraSpecial, icon: "/awakenings/Extra_Special.png" },
  { name: Awakening.FightOrFlight, icon: "/awakenings/Fight_or_Flight.png" },
  { name: Awakening.FireUp, icon: "/awakenings/Fire_Up!.png" },
  { name: Awakening.GlassCannon, icon: "/awakenings/Glass_Cannon.png" },
  { name: Awakening.HeavyImpact, icon: "/awakenings/Heavy_Impact.png" },
  { name: Awakening.Hotshot, icon: "/awakenings/Hotshot.png" },
  { name: Awakening.InnerFocus, icon: "/awakenings/Inner_Focus.png" },
  { name: Awakening.KnifesEdge, icon: "/awakenings/Knife's_Edge.png" },
  { name: Awakening.MightOfTheColossus, icon: "/awakenings/Might_of_the_Colossus.png" },
  { name: Awakening.MissilePropulsion, icon: "/awakenings/Missile_Propulsion.png" },
  { name: Awakening.Monumentalist, icon: "/awakenings/Monumentalist.png" },
  { name: Awakening.OmegaInfusedAccelerator, icon: "/awakenings/Omega_Infused_Accelerator.png" },
  { name: Awakening.OneTwoPunch, icon: "/awakenings/One-Two_Punch.png" },
  { name: Awakening.OrbDancer, icon: "/awakenings/Orb_Dancer.png" },
  { name: Awakening.OrbPonderer, icon: "/awakenings/Orb_Ponderer.png" },
  { name: Awakening.OrbReplicator, icon: "/awakenings/Orb_Replicator.png" },
  { name: Awakening.PeakPerformance, icon: "/awakenings/Peak_Performance.png" },
  { name: Awakening.PerfectForm, icon: "/awakenings/Perfect_Form.png" },
  { name: Awakening.Primetime, icon: "/awakenings/Primetime.png" },
  { name: Awakening.PrizeFighter, icon: "/awakenings/Prize_Fighter.png" },
  { name: Awakening.QuickStrike, icon: "/awakenings/Quick_Strike.png" },
  { name: Awakening.Rampage, icon: "/awakenings/Rampage.png" },
  { name: Awakening.RapidFire, icon: "/awakenings/Rapid_Fire.png" },
  { name: Awakening.RecoveryDrone, icon: "/awakenings/Recovery_Drone.png" },
  { name: Awakening.ReptileRemedy, icon: "/awakenings/Reptile_Remedy.png" },
  { name: Awakening.Reverberation, icon: "/awakenings/Reverberation.png" },
  { name: Awakening.SiegeMachine, icon: "/awakenings/Siege_Machine.png" },
  { name: Awakening.SparkOfAgility, icon: "/awakenings/Spark_of_Agility.png" },
  { name: Awakening.SparkOfFocus, icon: "/awakenings/Spark_of_Focus.png" },
  { name: Awakening.SparkOfResilience, icon: "/awakenings/Spark_of_Resilience.png" },
  { name: Awakening.SparkOfStrength, icon: "/awakenings/Spark_of_Strength.png" },
  { name: Awakening.SpecializedTraining, icon: "/awakenings/Specialized_Training.png" },
  { name: Awakening.StacksOnStacks, icon: "/awakenings/Stacks_On_Stacks.png" },
  { name: Awakening.StaggerSwagger, icon: "/awakenings/Stagger_Swagger.png" },
  { name: Awakening.Stinger, icon: "/awakenings/Stinger.png" },
  { name: Awakening.SuperSurge, icon: "/awakenings/Super_Surge.png" },
  { name: Awakening.TeamPlayer, icon: "/awakenings/Team_Player.png" },
  { name: Awakening.TempoSwing, icon: "/awakenings/Tempo_Swing.png" },
  { name: Awakening.TimelessCreator, icon: "/awakenings/Timeless_Creator.png" },
  { name: Awakening.TwinDrive, icon: "/awakenings/Twin_Drive.png" },
  { name: Awakening.Unstoppable, icon: "/awakenings/Unstoppable.png" },
];

export const CURRENT_AWAKENING_POOL = [
  Awakening.AmongTitans,
  Awakening.Aerials,
  Awakening.Berserker,
  Awakening.BuiltDifferent,
  Awakening.BulkUp,
  Awakening.CastToLast,
  Awakening.Deadeye,
  Awakening.Demolitionist,
  Awakening.ExplosiveEntrance,
  Awakening.ExtraSpecial,
  Awakening.GlassCannon,
  Awakening.HeavyImpact,
  Awakening.Hotshot,
  Awakening.InnerFocus,
  Awakening.MissilePropulsion,
  Awakening.Monumentalist,
  Awakening.OmegaInfusedAccelerator,
  Awakening.OneTwoPunch,
  Awakening.OrbDancer,
  Awakening.PeakPerformance,
  Awakening.Primetime,
  Awakening.PrizeFighter,
  Awakening.QuickStrike,
  Awakening.Rampage,
  Awakening.ReptileRemedy,
  Awakening.SiegeMachine,
  Awakening.SpecializedTraining,
  Awakening.StacksOnStacks,
  Awakening.Stinger,
  Awakening.SuperSurge,
  Awakening.TeamPlayer,
  Awakening.TempoSwing,
  Awakening.TimelessCreator,
  Awakening.TwinDrive,
];
