from enum import StrEnum


class Team(StrEnum):
    BLUE = "blue"
    RED = "red"
    SPECTATOR = "spectator"


class DraftAction(StrEnum):
    BAN = "ban"
    PICK = "pick"


class Awakening(StrEnum):
    AdrenalineRush = "Adrenaline Rush"
    Aerials = "Aerials"
    AmongTitans = "Among Titans"
    Berserker = "Berserker"
    BigFish = "Big Fish"
    BuiltDifferent = "Built Different"
    BulkUp = "Bulk Up"
    CastToLast = "Cast To Last"
    Catalyst = "Catalyst"
    Chronoboost = "Chronoboost"
    Deadeye = "Deadeye"
    Demolitionist = "Demolitionist"
    Egoist = "Egoist"
    ExplosiveEntrance = "Explosive Entrance"
    ExtraSpecial = "Extra Special"
    FightOrFlight = "Fight or Flight"
    FireUp = "Fire Up!"
    GlassCannon = "Glass Cannon"
    HeavyImpact = "Heavy Impact"
    Hotshot = "Hotshot"
    InnerFocus = "Inner Focus"
    KnifesEdge = "Knife's Edge"
    MightOfTheColossus = "Might of the Colossus"
    MissilePropulsion = "Missile Propulsion"
    Monumentalist = "Monumentalist"
    OmegaInfusedAccelerator = "Omega Infused Accelerator"
    OneTwoPunch = "One-Two Punch"
    OrbDancer = "Orb Dancer"
    OrbPonderer = "Orb Ponderer"
    OrbReplicator = "Orb Replicator"
    PeakPerformance = "Peak Performance"
    PerfectForm = "Perfect Form"
    Primetime = "Primetime"
    PrizeFighter = "Prize Fighter"
    QuickStrike = "Quick Strike"
    Rampage = "Rampage"
    RapidFire = "Rapid Fire"
    RecoveryDrone = "Recovery Drone"
    ReptileRemedy = "Reptile Remedy"
    Reverberation = "Reverberation"
    SiegeMachine = "Siege Machine"
    SparkOfAgility = "Spark of Agility"
    SparkOfFocus = "Spark of Focus"
    SparkOfResilience = "Spark of Resilience"
    SparkOfStrength = "Spark of Strength"
    SparkOfLeadership = "Spark of Leadership"
    SpecializedTraining = "Specialized Training"
    StacksOnStacks = "Stacks On Stacks"
    StaggerSwagger = "Stagger Swagger"
    Stinger = "Stinger"
    SuperSurge = "Super Surge"
    TeamPlayer = "Team Player"
    TempoSwing = "Tempo Swing"
    TimelessCreator = "Timeless Creator"
    TwinDrive = "Twin Drive"
    Unstoppable = "Unstoppable"


ALL_AWAKENINGS = list(Awakening)

CURRENT_AWAKENING_POOL = [
    Awakening.AmongTitans,
    Awakening.Aerials,
    Awakening.Berserker,
    Awakening.BuiltDifferent,
    Awakening.BulkUp,
    Awakening.CastToLast,
    Awakening.Deadeye,
    Awakening.Demolitionist,
    Awakening.ExplosiveEntrance,
    Awakening.ExtraSpecial,
    Awakening.GlassCannon,
    Awakening.HeavyImpact,
    Awakening.Hotshot,
    Awakening.InnerFocus,
    Awakening.MissilePropulsion,
    Awakening.Monumentalist,
    Awakening.OmegaInfusedAccelerator,
    Awakening.OneTwoPunch,
    Awakening.OrbDancer,
    Awakening.PeakPerformance,
    Awakening.Primetime,
    Awakening.PrizeFighter,
    Awakening.QuickStrike,
    Awakening.Rampage,
    Awakening.ReptileRemedy,
    Awakening.SiegeMachine,
    Awakening.SpecializedTraining,
    Awakening.StacksOnStacks,
    Awakening.Stinger,
    Awakening.SuperSurge,
    Awakening.TeamPlayer,
    Awakening.TempoSwing,
    Awakening.TimelessCreator,
    Awakening.TwinDrive,
]

AWAKENING_CONFLICTS: dict[Awakening, list[Awakening]] = {
    Awakening.SparkOfResilience: [
        Awakening.SparkOfStrength,
        Awakening.SparkOfAgility,
        Awakening.SparkOfFocus,
        Awakening.BigFish,
        Awakening.StaggerSwagger,
        Awakening.BulkUp,
        Awakening.PeakPerformance,
        Awakening.TempoSwing,
        Awakening.OrbPonderer,
        Awakening.OrbDancer,
        Awakening.Reverberation,
        Awakening.SparkOfLeadership,
        Awakening.Unstoppable,
        Awakening.RecoveryDrone,
        Awakening.ReptileRemedy,
        Awakening.Catalyst,
    ],
    Awakening.SparkOfFocus: [
        Awakening.SparkOfResilience,
        Awakening.SparkOfStrength,
        Awakening.SparkOfAgility,
        Awakening.ExtraSpecial,
        Awakening.RapidFire,
        Awakening.Primetime,
        Awakening.PerfectForm,
        Awakening.TwinDrive,
        Awakening.Hotshot,
        Awakening.AdrenalineRush,
        Awakening.HeavyImpact,
        Awakening.OrbPonderer,
        Awakening.OrbDancer,
        Awakening.Reverberation,
        Awakening.SparkOfLeadership,
    ],
    Awakening.SparkOfStrength: [
        Awakening.SparkOfFocus,
        Awakening.SparkOfResilience,
        Awakening.SparkOfAgility,
        Awakening.SpecializedTraining,
        Awakening.AdrenalineRush,
        Awakening.PrizeFighter,
        Awakening.HeavyImpact,
        Awakening.BulkUp,
        Awakening.SuperSurge,
        Awakening.GlassCannon,
        Awakening.OrbPonderer,
        Awakening.OrbDancer,
        Awakening.SparkOfLeadership,
        Awakening.OneTwoPunch,
        Awakening.ExplosiveEntrance,
        Awakening.Stinger,
        Awakening.MightOfTheColossus,
    ],
    Awakening.SparkOfAgility: [
        Awakening.SparkOfFocus,
        Awakening.SparkOfResilience,
        Awakening.SparkOfStrength,
        Awakening.StacksOnStacks,
        Awakening.Chronoboost,
        Awakening.GlassCannon,
        Awakening.PeakPerformance,
        Awakening.SuperSurge,
        Awakening.Aerials,
        Awakening.FightOrFlight,
        Awakening.OrbDancer,
        Awakening.AmongTitans,
        Awakening.SparkOfLeadership,
        Awakening.OrbPonderer,
        Awakening.ExplosiveEntrance,
        Awakening.Egoist,
        Awakening.KnifesEdge,
    ],
    Awakening.ExtraSpecial: [
        Awakening.SpecializedTraining,
        Awakening.TwinDrive,
        Awakening.RapidFire,
        Awakening.SparkOfFocus,
        Awakening.OrbPonderer,
    ],
    Awakening.SpecializedTraining: [
        Awakening.ExtraSpecial,
        Awakening.SparkOfStrength,
        Awakening.AdrenalineRush,
        Awakening.Stinger,
        Awakening.Deadeye,
        Awakening.BulkUp,
        Awakening.PrizeFighter,
        Awakening.MightOfTheColossus,
    ],
    Awakening.RapidFire: [
        Awakening.Primetime,
        Awakening.ExtraSpecial,
        Awakening.TwinDrive,
        Awakening.Hotshot,
        Awakening.SparkOfFocus,
        Awakening.Reverberation,
        Awakening.OrbPonderer,
    ],
    Awakening.Primetime: [
        Awakening.RapidFire,
        Awakening.SparkOfFocus,
        Awakening.Reverberation,
        Awakening.Stinger,
    ],
    Awakening.Deadeye: [
        Awakening.MissilePropulsion,
        Awakening.Aerials,
        Awakening.GlassCannon,
        Awakening.SiegeMachine,
        Awakening.Stinger,
        Awakening.SpecializedTraining,
    ],
    Awakening.MissilePropulsion: [
        Awakening.Deadeye,
        Awakening.Aerials,
        Awakening.GlassCannon,
        Awakening.SiegeMachine,
        Awakening.Stinger,
    ],
    Awakening.PerfectForm: [
        Awakening.HeavyImpact,
        Awakening.TempoSwing,
        Awakening.SparkOfFocus,
        Awakening.OneTwoPunch,
        Awakening.OrbPonderer,
    ],
    Awakening.TwinDrive: [
        Awakening.SuperSurge,
        Awakening.Chronoboost,
        Awakening.Aerials,
        Awakening.RapidFire,
        Awakening.ExtraSpecial,
        Awakening.SparkOfFocus,
        Awakening.FightOrFlight,
        Awakening.OrbPonderer,
        Awakening.ExplosiveEntrance,
    ],
    Awakening.SuperSurge: [
        Awakening.TwinDrive,
        Awakening.Chronoboost,
        Awakening.Aerials,
        Awakening.SparkOfStrength,
        Awakening.SparkOfAgility,
        Awakening.ExplosiveEntrance,
        Awakening.Stinger,
        Awakening.MightOfTheColossus,
    ],
    Awakening.CastToLast: [
        Awakening.Chronoboost,
        Awakening.TimelessCreator,
        Awakening.Monumentalist,
        Awakening.SiegeMachine,
    ],
    Awakening.Monumentalist: [
        Awakening.TimelessCreator,
        Awakening.CastToLast,
        Awakening.SiegeMachine,
    ],
    Awakening.TimelessCreator: [
        Awakening.Monumentalist,
        Awakening.CastToLast,
        Awakening.SiegeMachine,
    ],
    Awakening.Hotshot: [
        Awakening.RapidFire,
        Awakening.SparkOfFocus,
        Awakening.TeamPlayer,
        Awakening.Reverberation,
    ],
    Awakening.AdrenalineRush: [
        Awakening.PrizeFighter,
        Awakening.SpecializedTraining,
        Awakening.OneTwoPunch,
        Awakening.SparkOfFocus,
        Awakening.Reverberation,
        Awakening.Demolitionist,
        Awakening.Stinger,
        Awakening.MightOfTheColossus,
    ],
    Awakening.PrizeFighter: [
        Awakening.AdrenalineRush,
        Awakening.SparkOfStrength,
        Awakening.RecoveryDrone,
        Awakening.Stinger,
        Awakening.SpecializedTraining,
        Awakening.MightOfTheColossus,
    ],
    Awakening.Stinger: [
        Awakening.RapidFire,
        Awakening.MissilePropulsion,
        Awakening.AdrenalineRush,
        Awakening.SparkOfStrength,
        Awakening.HeavyImpact,
        Awakening.OneTwoPunch,
        Awakening.BulkUp,
        Awakening.SuperSurge,
        Awakening.ExplosiveEntrance,
        Awakening.SpecializedTraining,
        Awakening.Deadeye,
        Awakening.Primetime,
        Awakening.PrizeFighter,
        Awakening.MightOfTheColossus,
    ],
    Awakening.BuiltDifferent: [
        Awakening.BigFish,
        Awakening.HeavyImpact,
        Awakening.SparkOfStrength,
        Awakening.Demolitionist,
        Awakening.RecoveryDrone,
        Awakening.ExplosiveEntrance,
        Awakening.Rampage,
        Awakening.MightOfTheColossus,
    ],
    Awakening.BigFish: [
        Awakening.BuiltDifferent,
        Awakening.SparkOfResilience,
        Awakening.PeakPerformance,
        Awakening.BulkUp,
        Awakening.StaggerSwagger,
        Awakening.TempoSwing,
        Awakening.Reverberation,
        Awakening.Demolitionist,
        Awakening.Unstoppable,
        Awakening.RecoveryDrone,
        Awakening.ReptileRemedy,
        Awakening.Rampage,
        Awakening.MightOfTheColossus,
        Awakening.Catalyst,
    ],
    Awakening.StaggerSwagger: [
        Awakening.BigFish,
        Awakening.BulkUp,
        Awakening.PeakPerformance,
        Awakening.SparkOfResilience,
        Awakening.TempoSwing,
        Awakening.Stinger,
        Awakening.Reverberation,
        Awakening.AmongTitans,
        Awakening.FightOrFlight,
        Awakening.Unstoppable,
        Awakening.ReptileRemedy,
        Awakening.Rampage,
        Awakening.Catalyst,
        Awakening.Egoist,
        Awakening.KnifesEdge,
    ],
    Awakening.OneTwoPunch: [
        Awakening.PerfectForm,
        Awakening.HeavyImpact,
        Awakening.SparkOfStrength,
        Awakening.AdrenalineRush,
        Awakening.ExplosiveEntrance,
        Awakening.Stinger,
        Awakening.MightOfTheColossus,
    ],
    Awakening.StacksOnStacks: [
        Awakening.StaggerSwagger,
        Awakening.GlassCannon,
        Awakening.SparkOfAgility,
        Awakening.Rampage,
        Awakening.AmongTitans,
        Awakening.FightOrFlight,
        Awakening.OrbDancer,
        Awakening.Unstoppable,
        Awakening.RecoveryDrone,
        Awakening.ReptileRemedy,
        Awakening.Egoist,
        Awakening.KnifesEdge,
    ],
    Awakening.Chronoboost: [
        Awakening.SuperSurge,
        Awakening.CastToLast,
        Awakening.Aerials,
        Awakening.TwinDrive,
        Awakening.SparkOfAgility,
        Awakening.ExplosiveEntrance,
    ],
    Awakening.GlassCannon: [
        Awakening.StacksOnStacks,
        Awakening.Deadeye,
        Awakening.MissilePropulsion,
        Awakening.Aerials,
        Awakening.SparkOfAgility,
        Awakening.SparkOfStrength,
        Awakening.AmongTitans,
        Awakening.KnifesEdge,
        Awakening.OrbDancer,
        Awakening.Unstoppable,
        Awakening.MightOfTheColossus,
        Awakening.Egoist,
        Awakening.FightOrFlight,
    ],
    Awakening.HeavyImpact: [
        Awakening.BuiltDifferent,
        Awakening.PerfectForm,
        Awakening.OneTwoPunch,
        Awakening.SparkOfStrength,
        Awakening.SparkOfFocus,
        Awakening.Reverberation,
        Awakening.OrbPonderer,
        Awakening.ExplosiveEntrance,
        Awakening.Stinger,
        Awakening.MightOfTheColossus,
    ],
    Awakening.PeakPerformance: [
        Awakening.StaggerSwagger,
        Awakening.BigFish,
        Awakening.BulkUp,
        Awakening.SparkOfResilience,
        Awakening.SparkOfAgility,
        Awakening.TempoSwing,
        Awakening.ReptileRemedy,
        Awakening.AmongTitans,
        Awakening.Reverberation,
        Awakening.OrbDancer,
        Awakening.Unstoppable,
        Awakening.Catalyst,
        Awakening.Egoist,
        Awakening.FightOrFlight,
        Awakening.KnifesEdge,
    ],
    Awakening.BulkUp: [
        Awakening.StaggerSwagger,
        Awakening.BigFish,
        Awakening.PeakPerformance,
        Awakening.SparkOfResilience,
        Awakening.SparkOfStrength,
        Awakening.TempoSwing,
        Awakening.Stinger,
        Awakening.Reverberation,
        Awakening.Unstoppable,
        Awakening.SpecializedTraining,
        Awakening.ReptileRemedy,
        Awakening.MightOfTheColossus,
        Awakening.Catalyst,
    ],
    Awakening.Aerials: [
        Awakening.Deadeye,
        Awakening.MissilePropulsion,
        Awakening.SuperSurge,
        Awakening.Chronoboost,
        Awakening.GlassCannon,
        Awakening.SparkOfAgility,
        Awakening.ExplosiveEntrance,
        Awakening.SiegeMachine,
    ],
    Awakening.QuickStrike: [
        Awakening.Hotshot,
        Awakening.BuiltDifferent,
        Awakening.BigFish,
        Awakening.Demolitionist,
        Awakening.TeamPlayer,
        Awakening.Catalyst,
        Awakening.Egoist,
        Awakening.FireUp,
        Awakening.FightOrFlight,
        Awakening.RecoveryDrone,
        Awakening.Rampage,
        Awakening.MightOfTheColossus,
    ],
    Awakening.TempoSwing: [
        Awakening.PerfectForm,
        Awakening.BigFish,
        Awakening.BulkUp,
        Awakening.PeakPerformance,
        Awakening.SparkOfResilience,
        Awakening.StaggerSwagger,
        Awakening.Reverberation,
        Awakening.Unstoppable,
        Awakening.Stinger,
        Awakening.Rampage,
        Awakening.ReptileRemedy,
    ],
    Awakening.OrbDancer: [
        Awakening.OrbPonderer,
        Awakening.StacksOnStacks,
        Awakening.StaggerSwagger,
        Awakening.SparkOfAgility,
        Awakening.SparkOfFocus,
        Awakening.SparkOfResilience,
        Awakening.SparkOfStrength,
        Awakening.GlassCannon,
        Awakening.PeakPerformance,
        Awakening.AmongTitans,
        Awakening.OrbReplicator,
        Awakening.SparkOfLeadership,
        Awakening.Unstoppable,
        Awakening.RecoveryDrone,
        Awakening.ReptileRemedy,
        Awakening.Egoist,
        Awakening.FightOrFlight,
        Awakening.KnifesEdge,
    ],
    Awakening.OrbPonderer: [
        Awakening.OrbDancer,
        Awakening.SparkOfFocus,
        Awakening.SparkOfResilience,
        Awakening.SparkOfStrength,
        Awakening.SparkOfAgility,
        Awakening.RapidFire,
        Awakening.TwinDrive,
        Awakening.PerfectForm,
        Awakening.HeavyImpact,
        Awakening.ExtraSpecial,
        Awakening.Reverberation,
        Awakening.OrbReplicator,
        Awakening.SparkOfLeadership,
        Awakening.Unstoppable,
        Awakening.RecoveryDrone,
        Awakening.ReptileRemedy,
        Awakening.Egoist,
        Awakening.FightOrFlight,
        Awakening.KnifesEdge,
    ],
    Awakening.OrbReplicator: [
        Awakening.OrbPonderer,
        Awakening.OrbDancer,
        Awakening.SparkOfLeadership,
        Awakening.FireUp,
        Awakening.TeamPlayer,
        Awakening.AmongTitans,
    ],
    Awakening.Reverberation: [
        Awakening.BigFish,
        Awakening.BulkUp,
        Awakening.PeakPerformance,
        Awakening.SparkOfResilience,
        Awakening.TempoSwing,
        Awakening.SparkOfFocus,
        Awakening.RapidFire,
        Awakening.OrbPonderer,
        Awakening.HeavyImpact,
        Awakening.AdrenalineRush,
        Awakening.Hotshot,
        Awakening.Unstoppable,
        Awakening.ReptileRemedy,
        Awakening.Catalyst,
    ],
    Awakening.Catalyst: [
        Awakening.Egoist,
        Awakening.FireUp,
        Awakening.QuickStrike,
        Awakening.BulkUp,
        Awakening.Reverberation,
        Awakening.PeakPerformance,
        Awakening.ReptileRemedy,
        Awakening.Unstoppable,
        Awakening.BigFish,
        Awakening.RecoveryDrone,
        Awakening.StaggerSwagger,
        Awakening.SparkOfResilience,
    ],
    Awakening.Egoist: [
        Awakening.FireUp,
        Awakening.Catalyst,
        Awakening.QuickStrike,
        Awakening.StaggerSwagger,
        Awakening.PeakPerformance,
        Awakening.AmongTitans,
        Awakening.SparkOfAgility,
        Awakening.KnifesEdge,
        Awakening.OrbDancer,
        Awakening.OrbPonderer,
        Awakening.StacksOnStacks,
        Awakening.GlassCannon,
        Awakening.FightOrFlight,
    ],
    Awakening.FireUp: [
        Awakening.Catalyst,
        Awakening.Egoist,
        Awakening.AmongTitans,
        Awakening.OrbReplicator,
        Awakening.TeamPlayer,
        Awakening.SparkOfLeadership,
        Awakening.QuickStrike,
    ],
    Awakening.AmongTitans: [
        Awakening.SparkOfAgility,
        Awakening.FireUp,
        Awakening.OrbReplicator,
        Awakening.OrbDancer,
        Awakening.StacksOnStacks,
        Awakening.StaggerSwagger,
        Awakening.PeakPerformance,
        Awakening.GlassCannon,
        Awakening.FightOrFlight,
        Awakening.TeamPlayer,
        Awakening.SparkOfLeadership,
        Awakening.MightOfTheColossus,
        Awakening.Egoist,
        Awakening.KnifesEdge,
    ],
    Awakening.Demolitionist: [
        Awakening.BuiltDifferent,
        Awakening.BigFish,
        Awakening.AdrenalineRush,
        Awakening.QuickStrike,
        Awakening.RecoveryDrone,
        Awakening.Rampage,
        Awakening.MightOfTheColossus,
    ],
    Awakening.FightOrFlight: [
        Awakening.TwinDrive,
        Awakening.StaggerSwagger,
        Awakening.AmongTitans,
        Awakening.StacksOnStacks,
        Awakening.KnifesEdge,
        Awakening.QuickStrike,
        Awakening.Rampage,
        Awakening.SparkOfAgility,
        Awakening.PeakPerformance,
        Awakening.GlassCannon,
        Awakening.OrbDancer,
        Awakening.OrbPonderer,
        Awakening.Egoist,
    ],
    Awakening.KnifesEdge: [
        Awakening.FightOrFlight,
        Awakening.GlassCannon,
        Awakening.Unstoppable,
        Awakening.RecoveryDrone,
        Awakening.PeakPerformance,
        Awakening.StacksOnStacks,
        Awakening.StaggerSwagger,
        Awakening.AmongTitans,
        Awakening.Egoist,
        Awakening.SparkOfAgility,
        Awakening.OrbDancer,
        Awakening.OrbPonderer,
    ],
    Awakening.TeamPlayer: [
        Awakening.FireUp,
        Awakening.OrbReplicator,
        Awakening.QuickStrike,
        Awakening.AmongTitans,
        Awakening.Hotshot,
        Awakening.SparkOfLeadership,
    ],
    Awakening.SparkOfLeadership: [
        Awakening.SparkOfStrength,
        Awakening.SparkOfFocus,
        Awakening.SparkOfResilience,
        Awakening.SparkOfAgility,
        Awakening.OrbReplicator,
        Awakening.OrbPonderer,
        Awakening.OrbDancer,
        Awakening.TeamPlayer,
        Awakening.FireUp,
        Awakening.AmongTitans,
    ],
    Awakening.Unstoppable: [
        Awakening.BigFish,
        Awakening.StaggerSwagger,
        Awakening.StacksOnStacks,
        Awakening.PeakPerformance,
        Awakening.BulkUp,
        Awakening.Reverberation,
        Awakening.TempoSwing,
        Awakening.OrbDancer,
        Awakening.OrbPonderer,
        Awakening.GlassCannon,
        Awakening.SparkOfResilience,
        Awakening.RecoveryDrone,
        Awakening.KnifesEdge,
        Awakening.ReptileRemedy,
        Awakening.Rampage,
        Awakening.Catalyst,
    ],
    Awakening.RecoveryDrone: [
        Awakening.BuiltDifferent,
        Awakening.BigFish,
        Awakening.Demolitionist,
        Awakening.Unstoppable,
        Awakening.StacksOnStacks,
        Awakening.KnifesEdge,
        Awakening.OrbDancer,
        Awakening.OrbPonderer,
        Awakening.PrizeFighter,
        Awakening.SparkOfResilience,
        Awakening.QuickStrike,
        Awakening.ReptileRemedy,
        Awakening.Rampage,
        Awakening.MightOfTheColossus,
        Awakening.StaggerSwagger,
        Awakening.Catalyst,
    ],
    Awakening.ExplosiveEntrance: [
        Awakening.BuiltDifferent,
        Awakening.HeavyImpact,
        Awakening.SuperSurge,
        Awakening.Aerials,
        Awakening.Chronoboost,
        Awakening.OneTwoPunch,
        Awakening.SparkOfStrength,
        Awakening.SparkOfAgility,
        Awakening.TwinDrive,
        Awakening.Stinger,
        Awakening.MightOfTheColossus,
    ],
    Awakening.SiegeMachine: [
        Awakening.Aerials,
        Awakening.MissilePropulsion,
        Awakening.Monumentalist,
        Awakening.TimelessCreator,
        Awakening.CastToLast,
        Awakening.Deadeye,
    ],
    Awakening.ReptileRemedy: [
        Awakening.BigFish,
        Awakening.BulkUp,
        Awakening.Reverberation,
        Awakening.PeakPerformance,
        Awakening.SparkOfResilience,
        Awakening.TempoSwing,
        Awakening.Unstoppable,
        Awakening.StaggerSwagger,
        Awakening.RecoveryDrone,
        Awakening.Rampage,
        Awakening.StacksOnStacks,
        Awakening.OrbPonderer,
        Awakening.OrbDancer,
        Awakening.Catalyst,
    ],
    Awakening.Rampage: [
        Awakening.BigFish,
        Awakening.BuiltDifferent,
        Awakening.RecoveryDrone,
        Awakening.Demolitionist,
        Awakening.QuickStrike,
        Awakening.FightOrFlight,
        Awakening.Unstoppable,
        Awakening.StacksOnStacks,
        Awakening.StaggerSwagger,
        Awakening.ReptileRemedy,
    ],
    Awakening.MightOfTheColossus: [
        Awakening.SpecializedTraining,
        Awakening.PrizeFighter,
        Awakening.AdrenalineRush,
        Awakening.OneTwoPunch,
        Awakening.HeavyImpact,
        Awakening.BulkUp,
        Awakening.SuperSurge,
        Awakening.GlassCannon,
        Awakening.ExplosiveEntrance,
        Awakening.Stinger,
        Awakening.SparkOfStrength,
        Awakening.BigFish,
        Awakening.BuiltDifferent,
        Awakening.RecoveryDrone,
        Awakening.Demolitionist,
        Awakening.AmongTitans,
        Awakening.QuickStrike,
        Awakening.TempoSwing,
    ],
}

TIMER_SECONDS = 30.0
